sudo: false
language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"

before_install:
  - sudo apt install gnupg

install:
  pip install tox-travis

script: tox

notifications:
  email: false

